import = ["/home/shashank/.config/alacritty/themes/themes/carbonfox.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "Full"
opacity = 1.0

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 15
y = 15

[cursor]
style = "block"
